# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-13 04:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purasche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Marca')),
                ('model', models.CharField(max_length=20, verbose_name='Modelo')),
                ('date_purasche', models.DateTimeField(auto_now=True, verbose_name='Fecha de Compra')),
                ('patent', models.CharField(max_length=10, null=True, verbose_name='Patente')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('repairs', models.IntegerField(verbose_name='Reparaciones')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aCount', to='ventas.Purasche')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
            },
        ),
    ]
